"""Initial schema — users, assets, prices, portfolios.

Revision ID: 0001_initial
Revises:
Create Date: 2026-04-28 16:00:00.000000

This is the first migration. It creates all four tables in dependency
order (assets/users → prices/portfolios) along with their indexes and
constraints.

Hand-written (not autogenerated) because we don't have a running DB
yet at the time we author this. Future migrations can use
`alembic revision --autogenerate` once the DB is up.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# Revision identifiers used by Alembic to track migration order.
revision: str = "0001_initial"
down_revision: Union[str, None] = None  # First migration — no parent.
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create all four tables.

    Order matters: assets/users have no FK dependencies and are created
    first. prices/portfolios reference them via FK.
    """

    # --- users ---
    op.create_table(
        "users",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime,
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.create_index("idx_users_email", "users", ["email"])

    # --- assets ---
    op.create_table(
        "assets",
        sa.Column("ticker", sa.String(10), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("asset_class", sa.String(20), nullable=False),
        sa.Column("is_curated", sa.Boolean, nullable=False, server_default=sa.text("FALSE")),
        sa.Column(
            "created_at",
            sa.DateTime,
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )

    # --- prices ---
    op.create_table(
        "prices",
        sa.Column(
            "ticker",
            sa.String(10),
            sa.ForeignKey("assets.ticker", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("date", sa.Date, primary_key=True),
        sa.Column("close", sa.Numeric(precision=12, scale=4), nullable=False),
    )
    # Extra index for "latest N years of TICKER" queries — uses DESC
    # so the DB can scan in reverse without sorting.
    op.create_index(
        "idx_prices_ticker_date_desc",
        "prices",
        ["ticker", sa.text("date DESC")],
    )

    # --- portfolios ---
    op.create_table(
        "portfolios",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column(
            "user_id",
            sa.Integer,
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime,
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        # Inputs
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("risk_level", sa.SmallInteger, nullable=False),
        sa.Column("horizon_years", sa.SmallInteger, nullable=False),
        sa.Column("target_volatility", sa.Numeric(precision=6, scale=4), nullable=False),
        # Outputs
        sa.Column("weights", JSONB, nullable=False),
        sa.Column("expected_return", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("expected_volatility", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("sharpe_ratio", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("mc_summary", JSONB, nullable=False),
        sa.Column("mc_seed", sa.Integer, nullable=False),
        # CHECK constraints — DB-level guard against bad data.
        sa.CheckConstraint("risk_level BETWEEN 1 AND 5", name="ck_risk_level_range"),
        sa.CheckConstraint("horizon_years BETWEEN 1 AND 30", name="ck_horizon_range"),
    )
    op.create_index(
        "idx_portfolios_user_created",
        "portfolios",
        ["user_id", sa.text("created_at DESC")],
    )


def downgrade() -> None:
    """Drop everything in reverse order (FKs respected)."""
    op.drop_index("idx_portfolios_user_created", table_name="portfolios")
    op.drop_table("portfolios")

    op.drop_index("idx_prices_ticker_date_desc", table_name="prices")
    op.drop_table("prices")

    op.drop_table("assets")

    op.drop_index("idx_users_email", table_name="users")
    op.drop_table("users")
